import { ISettings } from 'src/shared/types/settings';

export interface IStorage extends ISettings {
    isEnabled: boolean;
}

export const DEFAULT_STORAGE: IStorage = {
    isEnabled: true,
    hideShorts: { enabled: false },
    hideHoverPreview: { enabled: false },
    hideChannelBanner: { enabled: false },
    adsFeedVideo: { enabled: false },
    speedControl: { enabled: false, value: '1.00' },
    adsYoutubeBanner: { enabled: false },
    hideChannelTrailer: { enabled: false },
    autoNextShorts: { enabled: false },
    hideJams: { enabled: false },
    hideSearchTags: { enabled: false },
    hidePlayerSubtitlesButton: { enabled: false },
    hideCreateVideo: { enabled: false },
    voiceButtonInSearch: { enabled: false },
    hidePlayerWideSizePlayerButton: { enabled: false },
    hidePlayerMiniSizePlayerButton: { enabled: false },
    virtualKeyboard: { enabled: false },
    notificationButton: { enabled: false },
    hideYourMovies: { enabled: false },
    hideNewsSection: { enabled: false },
    hidePlayerAutoplay: { enabled: false },
    hideSidebar: { enabled: false },
    hideMenuShorts: { enabled: false },
    hideMenuPlaylists: { enabled: false },
    hideMenuYourVideo: { enabled: false },
    hideMenuHistory: { enabled: false },
    hideMenuWatchLater: { enabled: false },
    hideMenuLikedVideos: { enabled: false },
    hideMenuSubscriptionsList: { enabled: false },
    hideMenuExploreMusic: { enabled: false },
    hideMenuExploreGaming: { enabled: false },
    hideMenuExploreSports: { enabled: false },
    hideMenuExploreNews: { enabled: false },
    hideMenuExploreTrending: { enabled: false },
    hideMenuMorePremium: { enabled: false },
    hideMenuMoreKids: { enabled: false },
    hideMenuMoreMusic: { enabled: false },
    shortSpeedControl: { enabled: false },
    hideMenuMoreStudio: { enabled: false },
};
